
GlorifiedHandcuffs.i18n.RegisterPhrases( "ru", {
    cuffed = "Вы в наручниках",
    blindfolded = "Вы с завязанными глазами",
    gagged = "Вам заткнули рот",
    hitToFree = "Жми  %s  чтобы освободиться",
    brokenFreeWanted = "Побег из-под стражи",
    bailMenu = "Меню залога",
    bailPlayer = "Задержанный",
    bailNpc = "Залог NPC",
    jailerNpc = "Тюремщик NPC",
    noPlayers = "Нет арестованных игроков.",
    surrendering = "Вы сдаетесь",
    putHandsDown = "Нажми  %s  чтобы опустить руки",
    playersJailed = "Вы арестовали %s игрока(ов) на %s.",
    name = "Имя",
    job = "Работа",
    wallet = "Кошелёк",
    confiscateAll = "Конфисковать всё",
    confiscateIllegal = "Конфисковать нелегальное",
    takeAll = "Взять всё",
    takeIllegal = "Взять нелегальное",
    dragPlayer = "Отпустить игрока",
    blindfoldPlayer = "Завязать глаза",
    removeBlindfold = "Убрать повязку с глаз",
    gagPlayer = "Заткнуть игрока",
    removeGag = "Разрешить говорить",
    confiscate = "Конфисковать",
    handcuffs = "Наручники",
    baton = "Палка",
} )