
GlorifiedHandcuffs.i18n.RegisterPhrases( "fr", {
    cuffed = "Vous êtes menotté",
    blindfolded = "Vous avez les yeux bandés",
    gagged = "Vous êtes bâillonné",
    hitToFree = "Spam %s pour se libérer",
    brokenFreeWanted = "S'échapper de la détention",
    bailMenu = "Menu des cautions",
    bailPlayer = "Payer la caution",
    bailNpc = "Cautions",
    jailerNpc = "Gardien de Prison",
    noPlayers = "Il n'y a pas de joueurs arrêtés.",
    surrendering = "Vous avez les mains en l'air",
    putHandsDown = "Appuyer sur %s pour baisser vos mains",
    playersJailed = "Vous avez emprisonné %s joueur(s) pour %s.",
    name = "Nom",
    job = "Métier",
    wallet = "Portefeuille",
    confiscateAll = "Confisquer tout",
    confiscateIllegal = "Confisquer illégales",
    takeAll = "Prendre toutes",
    takeIllegal = "Prendre illégales",
    dragPlayer = "Tirer le joueur",
    blindfoldPlayer = "Bander les yeux",
    removeBlindfold = "Retirer les yeux bandés",
    gagPlayer = "Bâillonner le joueuer",
    removeGag = "Supprimer le bâillon",
    confiscate = "Confisquer",
    handcuffs = "Menottes",
    baton = "Bâton",
} )