
GlorifiedHandcuffs.i18n.RegisterPhrases( "fr", {
    cuffed = "Vous êtes menotté",
    blindfolded = "You are blindfolded",
    gagged = "You are gagged",
    hitToFree = "Spam %s pour se libérer",
    brokenFreeWanted = "S'échapper de la détention",
    bailMenu = "Menu des cautions",
    bailPlayer = "Payer la caution",
    bailNpc = "Cautions NPC",
    jailerNpc = "Geôlier NPC",
    noPlayers = "Il n'y a pas de joueurs arrêtés.",
    surrendering = "Vous vous rendez",
    putHandsDown = "Appuyer sur %s pour baisser vos mains",
    playersJailed = "Vous avez emprisonné %s pour %s.",
    name = "Nom",
    job = "Métier",
    wallet = "Portefeuille",
    confiscateAll = "Confisquer tout",
    confiscateIllegal = "Confisquer illégalement",
    takeAll = "Prendre toutes",
    takeIllegal = "Prendre illégal",
    dragPlayer = "Tirer le joueur",
    blindfoldPlayer = "Bandeau le joueuer",
    removeBlindfold = "Retirer les yeux bandés",
    gagPlayer = "Gag le joueuer",
    removeGag = "Supprimer le bâillon",
    confiscate = "Confisquer"
})