
GlorifiedHandcuffs.i18n.RegisterPhrases( "de", {
    cuffed = "Du bist gefesselt",
    blindfolded = "Deine Augen sind verbunden",
    gagged = "Du bist geknebelt",
    hitToFree = "Drücke schnell  %s  um dich zu befreien",
    brokenFreeWanted = "Ist aus der Haft entkommen",
    bailMenu = "Kauftions Menü",
    bailPlayer = "Kaution bezahlen",
    bailNpc = "Kautions NPC",
    jailerNpc = "Gefängniswärter NPC",
    noPlayers = "Keine Spieler sind verhaftet.",
    surrendering = "Du ergibst dich",
    putHandsDown = "Drücke  %s  um deine Hände runter zu nehmen",
    playersJailed = "You jailed %s player(s) for %s.",
    name = "Name",
    job = "Beruf",
    wallet = "Portemonnaie",
    confiscateAll = "Alles beschlagnahmen",
    confiscateIllegal = "Illegale beschlagnahmen",
    takeAll = "Alles nehmen",
    takeIllegal = "Illegale nehmen",
    dragPlayer = "Spieler ziehen",
    blindfoldPlayer = "Spieler Augen verbinden",
    removeBlindfold = "Augenbinde verbinden",
    gagPlayer = "Spieler Knebeln",
    removeGag = "Knebel entfernen",
    confiscate = "Beschlagnahmen",
    handcuffs = "Handschellen",
    baton = "Schlagstock",
} )