
GlorifiedHandcuffs.i18n.RegisterPhrases( "pl", {
    cuffed = "Jesteś zakuty w kajdanki",
    blindfolded = "Masz zasłonięte oczy",
    gagged = "Jesteś zakneblowany",
    hitToFree = "Spam  %s  aby się uwolnić",
    brokenFreeWanted = "Uciekł z aresztu",
    bailMenu = "Menu Kaucji",
    bailPlayer = "Poręczenia za gracza",
    bailNpc = "Kaucja NPC",
    jailerNpc = "Więzienny NPC",
    noPlayers = "Nie ma aresztowanych graczy.",
    surrendering = "Poddajesz się",
    putHandsDown = "Naciśnij  %s  żeby opuścić ręce",
    playersJailed = "uwięziłeś %s gracza(y) na %s.",
    name = "Imie",
    job = "Praca",
    wallet = "Portfel",
    confiscateAll = "Konfiskata wszystkiego",
    confiscateIllegal = "Konfiskata nielegalnego",
    takeAll = "Zabierz wszystkich",
    takeIllegal = "Zabierz nielegalnych",
    dragPlayer = "Przeciągnij Gracza",
    blindfoldPlayer = "zasloń oczy Graczowi",
    removeBlindfold = "Usuń opaskę.",
    gagPlayer = "Zaknebluj Gracza",
    removeGag = "Usun Knebel",
    confiscate = "Skonfiskować",
    handcuffs = "Kajdany",
    baton = "Pałka",
} )