
GlorifiedHandcuffs.i18n.RegisterPhrases( "en", {
    cuffed = "You are cuffed",
    blindfolded = "You are blindfolded",
    gagged = "You are gagged",
    hitToFree = "Spam  %s  to break free",
    brokenFreeWanted = "Escaped from custody",
    bailMenu = "Bail Menu",
    bailPlayer = "Bail Player",
    bailNpc = "Bail NPC",
    jailerNpc = "Jailer NPC",
    noPlayers = "There are no arrested players.",
    surrendering = "You are surrendering",
    putHandsDown = "Press  %s  to put your hands down",
    playersJailed = "You jailed %s player(s) for %s.",
    name = "Name",
    job = "Job",
    wallet = "Wallet",
    confiscateAll = "Confiscate All",
    confiscateIllegal = "Confiscate Illegal",
    takeAll = "Take All",
    takeIllegal = "Take Illegal",
    dragPlayer = "Drag Player",
    blindfoldPlayer = "Blindfold Player",
    removeBlindfold = "Remove Blindfold",
    gagPlayer = "Gag Player",
    removeGag = "Remove Gag",
    confiscate = "Confiscate",
} )