
GlorifiedHandcuffs.i18n.RegisterPhrases( "es-ES", {
    cuffed = "Estas esposado",
    blindfolded = "Estas cegado",
    gagged = "Estas silenciado",
    hitToFree = "Pulsa  %s  para escapar",
    brokenFreeWanted = "Has escapado de la custodia",
    bailMenu = "Menú de fianza",
    bailPlayer = "Paga la fianza de un jugador",
    bailNpc = "NPC de fianza",
    jailerNpc = "NPC de arresto",
    noPlayers = "No hay jugadores arrestados.",
    surrendering = "Te has rendido",
    putHandsDown = "Pulsa  %s  para bajar tus brazos",
    playersJailed = "Has arrestado al jugador %s por %s.",
    name = "Nombre",
    job = "Trabajo",
    wallet = "Billetera",
    confiscateAll = "Confiscar todo",
    confiscateIllegal = "Confiscar lo ilegal",
    takeAll = "Tomar todo",
    takeIllegal = "Tomar lo ilegal",
    dragPlayer = "Arrastrar jugador",
    blindfoldPlayer = "Cegar jugador",
    removeBlindfold = "Remover vendas de ojos",
    gagPlayer = "Silenciar Jugador",
    removeGag = "Remover venda de su boca",
    confiscate = "Confiscar",
    handcuffs = "Esposas",
    baton = "Bastón",
} )