
GlorifiedHandcuffs.i18n.RegisterPhrases( "tr", {
    cuffed = "Kelepçelisin",
    hitToFree = "%s tusuna spamlayarak kelepçeyi kırabilirsin",
    brokenFreeWanted = "Tutsaklıktan kaçtın",
    bailMenu = "Kefalet Menüsü",
    bailPlayer = "Oyuncunun Kefaletini Öde",
    bailNpc = "Kefalet NPC'si",
    jailerNpc = "Gardiyan NPC'si",
    noPlayers = "Tutuklu hiçbir oyuncu yok.",
    surrendering = "Teslim oluyorsun",
    putHandsDown = "Ellerini indirmek için %s tuşuna bas",
    playersJailed = "%s oyuncusunu %s süreliğine hapise attın.",
    name = "İsim",
    job = "Meslek",
    wallet = "Cüzdan",
    confiscateAll = "Tüm Eşyalarına El Koy",
    confiscateIllegal = "İllegal Eşyalarına El Koy",
    takeAll = "Hepsini Al",
    takeIllegal = "İllegalleri Al",
    dragPlayer = "Oyuncuyu Sürükle",
    blindfoldPlayer = "Oyuncunun Gözünü Bağla",
    removeBlindfold = "Göz Bağını Çıkar",
    gagPlayer = "Oyuncunun Ağzını Bağla",
    removeGag = "Oyuncunun Ağzını Aç",
    confiscate = "El Koy"
} )