
GlorifiedHandcuffs.i18n.RegisterPhrases( "tr", {
    cuffed = "Kelepçelisin",
    blindfolded = "Gözlerin bağlı",
    gagged = "Ağzın bağlı",
    hitToFree = "%s  tuşunu spamlayarak kelepçeden kurtulabilirsin",
    brokenFreeWanted = "Tutsaklıktan kaçtı",
    bailMenu = "Kefalet Menüsü",
    bailPlayer = "Oyuncunun Kefaletini Öde",
    bailNpc = "Kefalet NPC’si",
    jailerNpc = "Gardiyan NPC’si",
    noPlayers = "Tutuklu hiçbir oyuncu yok.",
    surrendering = "Teslim oluyorsun",
    putHandsDown = "Ellerini indirmek için %s  tuşuna bas",
    playersJailed = "%s’yı %s süreliğine hapise attın.",
    name = "İsim",
    job = "Meslek",
    wallet = "Cüzdan",
    confiscateAll = "Tüm Eşyalarına El Koy",
    confiscateIllegal = "İllegal Eşyalarına El Koy",
    takeAll = "Hepsini Al",
    takeIllegal = "İllegal Eşyasını Al",
    dragPlayer = "Oyuncuyu Sürükle",
    blindfoldPlayer = "Oyuncunun Gözlerini Bağla",
    removeBlindfold = "Göz Bağını Çıkar",
    gagPlayer = "Oyuncunun Ağzını Bağla",
    removeGag = "Oyuncunun Ağzını Çöz",
    confiscate = "El Koy",
    handcuffs = "Kelepçe",
    baton = "Cob",
} )